on: [push]

name: ContinuousDeployment

jobs:

  build-and-deploy:
    runs-on: alpine-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - run: |
        az deployment group create --resource-group rg-dataclean-deploy-dev --template-file src/azure/continuous-deployment/DataCleanContinuousDeployment.json --parameters src/azure/continuous-deployment/DataCleanContinuousDeployment.parameters.json --location westus2
