on: [push]

name: ContinuousDeployment

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - run: pwd
    - run: ls -la .
    - run: ls -la ..
    - run: ls -la ../..
    - run: ls -la data-clean-app
    - run: pwsh -File data-clean-app/src/azure/continuous-deployment/New-Deployment.ps1 -environment dev
        
