on: [push]

name: ContinuousDeployment

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    - run: pwd
    - run: ls
    - run: pwsh -File ./src/azure/continuous-deployment/New-Deployment.ps1 -environment dev
        
